SVG code clean up: remove useless clipPaths
iconoir-icons/iconoir pull request #366
Opened 2023-10-07 20:01 UTC by luxbe

Some icons (e.g. `apple-shortuts.svg`) contain useless `clipPath`s in the SVG that don't change the visuals of the icon at all - they are probably an editing artifact. To keep consistency and minify SVG sizes a bit, I removed these `clipPath` elements.

One exception to this is the `nibol-logo.svg`. Here, `clipPath`s actually shape the content itself, so they remain unchanged in this PR.

Let me know what you think and if there are any changes you would like to see implemented!

Great library btw - much love ❤️

2023-12-17 19:27 UTC, lucaburgio commented
Hi, thank you for the help.
The icons need the closing `</svg>` bracket.

2023-12-17 19:27 UTC, lucaburgio requested changes
The icons need the closing SVG bracket.

2023-12-18 12:48 UTC, luxbe commented
Hi,

I just checked all changed SVGs and they all contain the closing `</svg>` tag. Which icons are missing it? I will gladly implement the changes, I just don't see it right now :)

2024-01-27 08:33 UTC, lucaburgio approved these changes

2024-01-27 08:44 UTC, merged